"""initial schema

Revision ID: 7702ae8aba53
Revises: 
Create Date: 2026-09-15 17:48:00.708689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7702ae8aba53'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landslide_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('area_ha', sa.Float(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('severity', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('admin', 'officer', 'public', name='role', native_enum=False), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('opt_in_sms', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('slope', sa.Float(), nullable=True),
    sa.Column('aspect', sa.Float(), nullable=True),
    sa.Column('elevation', sa.Float(), nullable=True),
    sa.Column('lithology', sa.String(length=255), nullable=True),
    sa.Column('risk_level', sa.Enum('green', 'yellow', 'orange', 'red', name='risk_level', native_enum=False), nullable=False),
    sa.Column('risk_probability', sa.Float(), nullable=False),
    sa.Column('rainfall_current_mm', sa.Float(), nullable=False),
    sa.Column('swi_current', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_name'), 'zones', ['name'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('green', 'yellow', 'orange', 'red', name='risk_level', native_enum=False), nullable=False),
    sa.Column('kind', sa.Enum('landslide', 'flash_flood', 'monsoon', 'advisory', name='alert_kind', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('pending', 'delivered', 'failed', 'acknowledged', name='alert_status', native_enum=False), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('sms_sent', sa.Integer(), nullable=False),
    sa.Column('recipient_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_zone_id'), 'alerts', ['zone_id'], unique=False)
    op.create_table('rainfall_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_mm', sa.Float(), nullable=False),
    sa.Column('forecast_mm', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_id', 'timestamp', name='uq_rainfall_zone_ts')
    )
    op.create_index(op.f('ix_rainfall_readings_timestamp'), 'rainfall_readings', ['timestamp'], unique=False)
    op.create_index(op.f('ix_rainfall_readings_zone_id'), 'rainfall_readings', ['zone_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('submitted', 'verified', 'resolved', name='report_status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    op.create_index(op.f('ix_reports_zone_id'), 'reports', ['zone_id'], unique=False)
    op.create_table('risk_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('level', sa.Enum('green', 'yellow', 'orange', 'red', name='risk_level', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_id', 'timestamp', name='uq_risk_zone_ts')
    )
    op.create_index(op.f('ix_risk_scores_timestamp'), 'risk_scores', ['timestamp'], unique=False)
    op.create_index(op.f('ix_risk_scores_zone_id'), 'risk_scores', ['zone_id'], unique=False)
    op.create_table('swi_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('computed_swi', sa.Float(), nullable=False),
    sa.Column('satellite_swi', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_id', 'timestamp', name='uq_swi_zone_ts')
    )
    op.create_index(op.f('ix_swi_readings_timestamp'), 'swi_readings', ['timestamp'], unique=False)
    op.create_index(op.f('ix_swi_readings_zone_id'), 'swi_readings', ['zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_swi_readings_zone_id'), table_name='swi_readings')
    op.drop_index(op.f('ix_swi_readings_timestamp'), table_name='swi_readings')
    op.drop_table('swi_readings')
    op.drop_index(op.f('ix_risk_scores_zone_id'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_timestamp'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_reports_zone_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_rainfall_readings_zone_id'), table_name='rainfall_readings')
    op.drop_index(op.f('ix_rainfall_readings_timestamp'), table_name='rainfall_readings')
    op.drop_table('rainfall_readings')
    op.drop_index(op.f('ix_alerts_zone_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_zones_name'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('landslide_events')
    # ### end Alembic commands ###
