"""phase 2b model runs and risk model version

Revision ID: abd075c89bd9
Revises: c85d9a255d2e
Create Date: 2026-09-15 18:36:49.309303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abd075c89bd9'
down_revision: Union[str, Sequence[str], None] = 'c85d9a255d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('roc_auc', sa.Float(), nullable=True),
    sa.Column('n_samples', sa.Integer(), nullable=False),
    sa.Column('n_features', sa.Integer(), nullable=False),
    sa.Column('params', sa.String(length=500), nullable=True),
    sa.Column('confusion_matrix', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_runs_version'), 'model_runs', ['version'], unique=False)
    op.add_column('risk_scores', sa.Column('model_version', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_scores', 'model_version')
    op.drop_index(op.f('ix_model_runs_version'), table_name='model_runs')
    op.drop_table('model_runs')
    # ### end Alembic commands ###
