"""phase 2a geometry columns

Revision ID: c85d9a255d2e
Revises: 7702ae8aba53
Create Date: 2026-09-15 18:20:44.981681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c85d9a255d2e'
down_revision: Union[str, Sequence[str], None] = '7702ae8aba53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landslide_events', sa.Column('geom_wkt', sa.Text(), nullable=True))
    op.add_column('zones', sa.Column('geom_wkt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zones', 'geom_wkt')
    op.drop_column('landslide_events', 'geom_wkt')
    # ### end Alembic commands ###
